### PR TITLE
Add Elm logo

### PR DESCRIPTION
**Pull request by cuducos**
Complementing [vim-bootstrap PR #259](https://github.com/avelino/vim-bootstrap/pull/259).

### CODE REVIEW

**Review by cassiobotaro — APPROVED** [review]
LGTM

**Comment by cuducos** [comment]
```console
$ curl -I http://vim-bootstrap.com/assets/images/logo/elm.png
HTTP/1.1 404 Not Found
```
Have I done anything wrong or just a matter of time?

**Comment by avelino** [comment]
@cuducos done deploy

**Comment by cuducos** [comment]
Yay, tks ; )

**Pull request merged**
